### ISSUE TITLE
Fix sample texts overwrite from individual Fontsamplers not replacing the default texts

### ISSUE THREAD

**Issue by kontur** [kontur/fontsampler-wordpress-plugin#135]
In version 0.3.7 the option to overwrite the sample texts does get stored, but the Fontsamplers still render with the default sample texts.

**Comment by jeanbaptistemora** [comment]
Hello @kontur,

I have a problem with these texts on a fresh installation of your plugin, on version 0.4.4 from WP plugin repo.

It shows version 0.4.4 on WP interface but contains the old version (0.3.7 as far as I can tell) of the includes/interface.php file modified here : https://github.com/kontur/fontsampler-wordpress-plugin/commit/9684704b96716b4a22499d991a20194350741099

I thought it could be from a version error on WP repo but I just checked and the zip directly from github has the same problem.

I don't know if it concerns all the commits / releases you did since 0.3.7 but at least this file was not updated in the releases.


On another note : Thank you very much for your work, I have a designer who is delighted to be able to present his work so nicely on his new WP ;) I think you'll soon have a donation from him.

**Comment by kontur** [comment]
Thanks @jeanbaptistemora for reporting this. I had a quick look now and it appears you are right that the patch is not applied in the latest version on the WP registry. I have to do more thorough testing to see what went wrong here, but will try to amend soon.

**Comment by kontur** [comment]
The latest release of `0.4.5` should finally fix this, again.
