### ISSUE TITLE
fontsampler.event.afterinit not firing in Firefox

### ISSUE THREAD

**Issue by hamblyfreeman** [kontur/fontsampler-wordpress-plugin#160]
Hi there

I've got an issue where fontsampler.event.afterinit doesn't always fire in Firefox (works fine in Chrome).

On the occasion where this doesn't fire, I see the console warning:

> Will-change memory consumption is too high. Budget limit is the document surface area multiplied by 3 (2667868 px). Occurrences of will-change over the budget will be ignored.

Is there any reason why this would be? I currently run a bunch of JS wrap() commands on page load to restyle the type tester, and then reveal the whole block (by changing the opacity) on fontsampler.event.afterinit, but right now this last piece of the puzzle is only firing 50% of the time in Firefox.

Any advice appreciated.

**Comment by kontur** [comment]
Sorry for the late reply.

Well, to be perfectly honest I have never seen anything like that console warning, so you have my interest. Is there anything else about the setup you can tell me that might help shed some light on this? 
The fontsampler should out of the box be hidden and revealed only after init — why do you need to re-wrap this functionality, or what are you changing while hiding the fontsampler that you cannot otherwise achieve?

**Comment by kontur** [comment]
@hamblyfreeman Any more information on this issue?
