### ISSUE TITLE
Please add default common features.

### ISSUE THREAD

**Issue by DunwichType** [kontur/fontsampler-wordpress-plugin#23]
Settings should include a list of the common features that users can check to make them defaults for new samplers. There should also be an option to apple defaults to all samplers when they are changed.

**Comment by kontur** [comment]
I think this could be implemented with a checkbox on the fontsampler edit form that shows/hides the entire 'Common features' section. There also is the 'Opentype options' (0.0.2 onwards only, I think) which could also be minimized by default to declutter the interface. The 'Interface layout' could equally follow a default layout for all fontsamplers on a site.

**Comment by kontur** [comment]
This is now implemented and on the dev branch. Will come live with the next preview release `0.0.4`. The most tricky part was making the drag and drop sortable UI layout somehow stay in tune with this, but that might needs some more thought eventually as well - maybe saving the default layout with the default values in the settings as well.

Opentype features might also be a candidate for inclusion here, but: a) The vary from font to font, so from fontsampler to fontsampler and b) I would like to offer OT features more as a "whatever the font supports" checkbox eventually, so then might be the time to include these aspects to this default settings effort.

Thanks again for bringing up this idea. It was obvious now that I think about it, but maybe I pushed it off because it was quite some work to implement :)
