### ISSUE TITLE
Some issues with RTL Wordpress

### ISSUE THREAD

**Issue by shahabsiavash** [kontur/fontsampler-wordpress-plugin#73]
Hi,

First of all I have said this before on TypeDrawers, this is a great plugin. Love it. 

Secondly, I saw some minor issues that I wanted to mention here.

When your site is an RTL one, you probably install the compatible version of Wordpress which could be Persian or Arabic. For those users the plugin's admin area is English but in RTL alignment. So I wanted to propose if you like and it is possible I want to translate the plugin to Persian and then you can add that to the languages.

Also the sliders acting a little RTL and LTR at the same time :)
As you can see...

![untitled2](https://cloud.githubusercontent.com/assets/20119395/24277206/4746d34c-1059-11e7-9d41-67922f2d432c.jpg)

Number 1 should be on the right next to number 2.
Number 3 I don't know should be on the middle or right?
Number 5 should be at the end of the slider closer to number 4, I guess.

And if we could change those **px 47**, **px 0**, **% 110** it would be great. Because they should be on the right and also in Persian and RTL.

But the most important thing is the Name of the fonts, I saw in the plugin that it suppose to show the names that we choose while uploading them but in my case they are all the original font names. If you look at the screen capture here you can see that I gave them Persian custom names but in the top picture you can see they all have Latin font family names.

![untitled](https://cloud.githubusercontent.com/assets/20119395/24277359/3f92eb3a-105a-11e7-80c2-d542ff6b8bb7.jpg)

Great day and happy spring :)

**Comment by kontur** [comment]
Thanks for reporting these and offering a translation of the plugin!

I will look into those issues in separate one by one, in particular testing with a RTL Wordpress installation is something I've not done so far at all.

As for the translation of the plugin itself I have to look into adding that at some point, but currently other issues are higher on the list of priorities. Once I do, I will happily consult you for a Persian translation. 👍

**Comment by shahabsiavash** [comment]
Hi, any update on Font name options? :)

**Comment by kontur** [comment]
Been away on travels for the past two weeks. Last I've worked on options to automatically extract the file's font name on upload (to see when something's not right, also). Next steps would be to allow overriding it, both for the backend and the dropdown list for the frontend. Stay tuned ;)

**Comment by shahabsiavash** [comment]
> @shahabsiavash Would it be "labeltext number unit" in RTL, or "number unit labeltext", ideally?
Thanks for considering this. If you look at it RTL, it should be like this. I hope it's obvious.
![screenshots_2018-01-19-14-55-43](https://user-images.githubusercontent.com/20119395/35149129-3a652a34-fd2a-11e7-8455-19e75c9f17d1.png)

**Comment by kontur** [comment]
Yea, okay, thanks.

Is there any other text in the front end except the "Select a sample text" dropdown default? I think all other labels are editable in the backend anyway, because I though users might want to customize this anyway (i.e. beyond just translating it), so I might as well make this one editable. Of course adding translation for the defaults would be nice.

I understand there is also the A / A black and white inverting button which are script specific - I might consider those with more abstract shapes.

For the OT button and the opentype features list - should those be translatable, or is this anyway anglocentric terminology also in applications - i.e. is there even default translations for all of those?

Any other front end strings I am missing?

**Comment by shahabsiavash** [comment]
Sorry for the delay.
Yes, I think all of them are customizable. I don't see any other one needs to be changed.
The A/A thing could be done by some shapes as you said. And that's great :)
I never used OT button, because it wasn't necessary for me, but yeah, I think they should be remain as default because otherwise no one can understand them, I know I couldn't if they were Persian for example :D

**Comment by kontur** [comment]
Great, thank you for confirming.

I've been testing to implement defaults for the slider labels that match the Wordpress installation language. These would be the default slider labels (which can still be overwritten, of course, say if the user facing site language is different from the admin language, or a different label is desired) for new installations, and also there is an option to reset the slider labels to those defaults once they were changed. I added German and Finnish translations myself, but would you be willing to translate a few strings to Persian, so we'd get better coverage and testing of those features? If yes, have a look at [this file](https://github.com/kontur/fontsampler-wordpress-plugin/blob/dev/lang/fontsampler-de_DE.po), it is pretty self explanatory - you can post it here, or email me at support@underscoretype.com

**Comment by shahabsiavash** [comment]
Hi, yeah sure. Of course. I have sent it to you. Although I used an online PO editor. So I couldn't add a new language, but I replaced the German with Persian words. Hope it works.

If there are more please let me know. Glad to do that.

msgid ""
msgstr ""
"Project-Id-Version: fontsampler-de_DE.po conversion\n"
"Report-Msgid-Bugs-To: \n"
"POT-Creation-Date: 2018-01-21 11:04+0000\n"
"PO-Revision-Date: 2018-01-21 11:07+0000\n"
"Last-Translator: \n"
"Language-Team: German (Germany)\n"
"Language: de-DE\n"
"Plural-Forms: nplurals=2; plural=n != 1;\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=UTF-8\n"
"Content-Transfer-Encoding: 8bit\n"
"X-Loco-Source-Locale: fa_IR\n"
"X-Loco-Parser: loco_parse_po\n"
"X-Generator: Loco https://localise.biz/"

#. translators: Default label for font size slider in the front end
#: FontsamplerPlugin.php:90
msgid "Size"
msgstr "اندازه"

#. translators: Default label for letter spacing slider in the front end
#: FontsamplerPlugin.php:96
msgid "Letter spacing"
msgstr "فاصله حروف"

#. translators: Default label for the line height slider in the front end
#: FontsamplerPlugin.php:102
msgid "Line height"
msgstr "ارتفاع سطر"

#. translators: Default label for the buy button in the front end
#: FontsamplerPlugin.php:136
msgid "Buy"
msgstr "خرید"

#. translators: Default label for the specimen download button in the front end
#: FontsamplerPlugin.php:142
msgid "Specimen"
msgstr "نمونه‌نوشته"

#: includes/interface.php:84
msgid "Select a sample text"
msgstr "انتخاب یک متن نمونه"

**Comment by kontur** [comment]
Superb, thank you. I can add it to the correct language file myself. Would the [WP language locale](https://make.wordpress.org/polyglots/teams/) for these be "fa_IR" for Persian?

I'm doing a couple of more fixes to the admin interface in RTL also, but would you be able and willing to test a development version, like on a local or online **TEST** environment of your page to see what gives?

**Comment by shahabsiavash** [comment]
Yes, it's fa_IR.

Sure. just please let me know how it works and we'll do that.

**Comment by kontur** [comment]
Great, thanks so much! You can download a preview version of the plugin [here](https://github.com/kontur/fontsampler-wordpress-plugin/archive/intl.zip). In your **testing environment**, replace the "fontsampler" folder at /wp-content/plugins/fontsampler with the one from the downloaded zip. Make sure to keep a copy of your old one (somewhere outside the plugins directory) and also backup your database, or at least the four _fontsampler database tables in it.

When you now load your site in the frontend (might need to clear your cache / hardreload) these should change:
- Fontsampler UI blocks now align right to left and wrap to new rows starting from the right
- Some UI blocks should flow more naturally from right to left (OT select, Invert, Alignment control)
- All sliders should work right to left and have their labels in the right direction

When you load your backend, these should be changed:
- All tables (fontsamplers, fontsets) and their content are properly right to left
- All sliders should work right to left, like in the front end
- Many smaller layout fixes, also the Settings-reset button should now be correctly on the left bottom, no longer overlapping with the save button (that button will also reset all text strings, but obviously that will also reset all your other settings!)
- All Settings > Features > Details labels for size, line height and letter spacing should have a button next to the label to reset the label to the locale default, i.e. Persian for you

Also let me know if some of your frontend theme overwrites act funny, because I changed the markup for the sliders a little bit. Still missing is the option to reset the "Select a sample text" to the locale default - new installations will get the correct locale string, but they, too, might want to overwrite that. I'll add that option still to the Settings.

Sorry for the long wait to have the last of these things implemented, I appreciate you patience!

**Comment by shahabsiavash** [comment]
Hi again! 
I have installed the preview version on localhost. I hope that's all right. And I think everything is working (thanks to you) except the OT options which were outside the box.
And those px 32 should be 32 px but in the the same position they are now.

I've captured this. Please take a look and let me know if anything is missing or should be tested.

![ezgif com-video-to-gif 2](https://user-images.githubusercontent.com/20119395/35218813-4c536b72-ff85-11e7-88d2-3c53c401335d.gif)

**Comment by kontur** [comment]
Thanks for testing! The OT modal needs fixing for RTL and LTR. This, plus the option to set the "select text" string will still be added, then this can ship with the next update.

**Comment by shahabsiavash** [comment]
Wonderful! Thanks.

**Comment by kontur** [comment]
@shahabsiavash Also, I would like to start listing (and linking to their website, if wanted) translators, starting with you. If you wish to be included in the about page like other contributors for translations please let me know what name or nick to use and if to link to some page of yours :)

**Comment by shahabsiavash** [comment]
Hi, "Select a language" would be: "انتخاب یک زبان".

And for the next comment, thanks for the offer. You could use my everywhere username: **Si47ash** and the website is **[shahabsiavash.com](url)** if it's ok. 

Thanks again.

**Comment by kontur** [comment]
The 0.4.0 update is now available via the Plugin registry. Thanks again for your help with the translation and debugging this! Let me know if you find anything out of place in regard to this.
