### ISSUE TITLE
A little change in font path

### ISSUE THREAD

**Issue by shahabsiavash** [kontur/fontsampler-wordpress-plugin#76]
Although it is necessary to not use a full functional font for a preview but it would be nice if the path of the fonts could not be (at least easily) found.

**Comment by kontur** [comment]
I appreciate your input on this. While obfuscating the path would be possible, the fact remains that straight in the chrome dev tools you can right click and save any loaded webfont, no matter what the path.
Having some protection on the path to prevent hotlinking might be one small measure and I'll confider implementing it, but overall webfonts are designed to be downloaded to the users computer, so I don't believe in security through obscurity. The only true way to circumvent downloading the fonts to visitors' computers is by rendering them as images, which seems to defeat the whole purpose of an interactive preview, no matter how sophisticated the implementation.

**Comment by shahabsiavash** [comment]
You're welcome. :)
That'a true. As we talked in an email conversation I would totally agree. Big foundries have this problem. I think I could only name MyFonts and as you said they are using an image rendering system. 

Thanks for doing that to make it much more harder :)

**Comment by kontur** [comment]
This could be implemented by serving all Fontsampler woff files via a proxy that hides the real file URL. The transmitted content, however, can still be copied to the computer.

**Comment by shahabsiavash** [comment]
I know that almost every option has been discussed here in the issues about this.

Buy how about the plugin has both options: 1- Text  and 2- Image

Is it totally a new thing to create images of input text? Because if the plugin has both, it would be functional for both groups. Those who like the load time more and those who like to protect the fonts. In the second solution, people can actually use the original font, because in some cases like Arabic/Persian it is not a good experience if we remove some glyphs, because glyphs are cursive and if you remove the middle ones the words get distorted and you don't remo e enoigh it can be easily recreated. Again because in Persian / Arabic you can basically copy on set of glyphs of a single letter and add some dots or remove aome and create another letter...

**Comment by kontur** [comment]
Right, well I've seen some foundry sites that use this kind of image system where you type, the info is sent to the server, which sends back an image.

Personally I don't think it is good performance, but I understand that some owners might be willing to make that sacrifice. However, it is also quite a considerable development effort to implement this kind of on the fly image rendering to integrate well with what now is essentially a full html interface.
Furthermore, the image based approaches don't get to profit from the browsers native text rendering, so text might actually look very much different than when rendered with the actual woff file.

I have another issue open to gather ideas for improving "security" of the fonts, but for this issue of hiding the Wordpress upload paths I feel it would be easy to add in the future, so that's a go from my behalf.

**Comment by shahabsiavash** [comment]
Thanks. I hope you can find some help from the community to make it easier to handle the issues and new features. :)

**Comment by kontur** [comment]
This is implemented as Setting in `0.4.5` that was just released 👍
